-- 1. Create the 'products' table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  category VARCHAR(100) NOT NULL,
  image_url TEXT,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Allow anonymous read access (so anyone can see the products in your shop)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access" ON products;
CREATE POLICY "Allow public read access" 
ON products 
FOR SELECT 
TO public 
USING (true);

-- 3. Insert luxury sample data
INSERT INTO products (name, price, category, image_url, description) VALUES
('Silk Evening Gown', 1200.00, 'Women', 'https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?q=80&w=2942&auto=format&fit=crop', 'Elegant silk evening gown perfect for formal events.'),
('Classic Wool Blazer', 850.00, 'Men', 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?q=80&w=2800&auto=format&fit=crop', 'Tailored classic wool blazer for a timeless look.'),
('Leather Crossbody Bag', 450.00, 'Accessories', 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=2938&auto=format&fit=crop', 'Minimalist genuine leather crossbody bag.'),
('Chrono Dress Watch', 1500.00, 'Accessories', 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=2899&auto=format&fit=crop', 'Premium automatic chronometric dress watch.'),
('Tailored Trousers', 350.00, 'Men', 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?q=80&w=2808&auto=format&fit=crop', 'Slim-fit tailored trousers crafted from fine wool blend.');
